Normalisation etc
edbennett/glue_analysis pull request #35
Opened 2023-11-16 14:12 UTC by edbennett

Fixes #27 and #28, and stops pytest picking up the example file (although doesn't do any of the things in #4 to make it runnable for people other than us)

2023-11-16 14:14 UTC, edbennett commented
Ah, this is another reason why messing around in your local git submodule copy is messy—I hadn't installed `pre-commit` into that one.

2023-11-16 18:20 UTC, chillenzer requested changes
Hi, nice work! The main function has a good clear structure and the delegates are short and well understandable. Three missing tests have I spotted:
- The check for missing `NT` or `num_configs` is untested.
- The check for missing divisibility is untested.
- The renaming in `_read_correlator_file` and `_read_vev_file` is untested (because I made wrong column names in the test data --> change column names in test data and check that the renaming works correctly).

2023-11-16 18:20 UTC, chillenzer commented on glue_analysis/readers/read_fortran.py
> +    correlators.correlators["channel"] = channel
Move this line up line 98 (just below `correlators.correlators = ...` to make the symmetry with the `vevs` case explicit.

2023-11-16 18:20 UTC, chillenzer commented on test/test_correlator.py
> +                corr_np[:, i, j] - vevs_np[i] * vevs_np[j]
Totally unrelated but I'm really glad that this line changes because it triggers one of the discrepancies between `black` and `ruff format` and as my `vim` is configured to run `black` and the pre-commit hooks run `ruff format`, it is changing back and forth in my working directory on every commit/save of the file.

2023-11-16 18:20 UTC, chillenzer commented on test/test_read_fortran.py
> +    NT = 24
Maybe rather lowercase?

2023-11-16 18:20 UTC, chillenzer commented on test/test_read_fortran.py
> +def test_read_correlators_fortran_preserves_normalised_data_in_vev(
We should probably test this for two or three combinations of values. The simplest possible implementation to pass this test does not have the full functionality. It's a simple `@pytest.mark.parametrize()`.

2023-11-16 18:20 UTC, chillenzer commented on test/test_read_fortran.py
> +    normalised_vev_data = np.concatenate(
This looks surprising. Isn't this just:
```python3
vev_data[:,-1] /= normalisation
```

2023-11-16 23:11 UTC, edbennett commented on glue_analysis/correlator.py
>          return max(self._correlators.Time)
A good name, but not the right one—now that `NT` is used for the temporal extent of the lattice itself, the only times we use this property are where we want to know how many time slices we have. Rather than imposing an extra constraint on the time indexing (which in principle could be zero- or one-based) and associated extra logic, I think it makes more sense to change this to `num_timeslices` to match `num_internal` and `num_samples`.

2023-11-16 23:12 UTC, edbennett commented on glue_analysis/correlator.py
> +            self.num_samples, self.max_time, self.num_internal, self.num_internal
I agree, but have been more extreme about it—see comment on the previous point (which I wrote before reading this).

2023-11-16 23:13 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +            "Op2_index": "Internal2",
Nope, this was a change to the data format by Andreas. It was easier to change the code than ask him to regenerate everything with different headers. If things come in inconsistently then I'll have to prod him about it.

2023-11-16 23:26 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +            "Op2_index": "Internal2",
The tests were ignoring the fact that the reader is supposed to rename the columns from the convention in the file to the convention we use internally. Updated.

2023-11-16 23:30 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +def _normalise_vevs(vevs: pd.DataFrame, NT: int, num_configs: int) -> None:
I thought about this, but similar to a previous discussion, our choices are:

 - Return an object that we've just mutated. Not actually functional, and may give the false impression that this is a fresh object.
 - Create a copy of something that may be pretty large in memory. Admittedly the vevs are O(`num_internal`) smaller than the correlators, but still it could be a hefty copy. (In the analysis run I did today, one run was using 20% of my system's memory already, and that was with binned data.)

I decided that in this case since mutation in place is what is happening anyway, making it explicit in the usage of the function was preferable. I'm open to being convinced otherwise though.

2023-11-16 23:31 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +        metadata.get("num_configs", 0), correlators.num_samples
One day I will learn not to play code golf in production code. Today is probably not that day.

2023-11-16 23:39 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +def _check_ensemble_divisibility(num_configs: int, num_samples: int) -> None:
Would you consider adding a `strict` or `raise` parameter to the function that enables `raise`ing in case the check fails to be an alternative?

2023-11-16 23:47 UTC, edbennett commented on test/test_read_fortran.py
> +    normalised_vev_data = np.concatenate(
…Yes. I'm not sure why I was worried about mutating `vev_data`, but even then the two lines to make a copy and normalise the right axis would be less than what's there.

2023-11-16 23:50 UTC, edbennett commented on test/test_read_fortran.py
> +    normalised_vev_data = np.concatenate(
Ah!

```
>       vev_data[:, -1] /= normalisation
E       numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'divide' output from dtype('float64') to dtype('int64') with casting rule 'same_kind'
```

So the copy is needed.

2023-11-16 23:56 UTC, edbennett commented on test/test_read_fortran.py
> +    NT = 24
I find lowercase `nt` really weird to read for some reason. I've found a compromise—I don't think it makes sense for everywhere (as it's verbose) but is OK for here (at the expense of consistency)

2023-11-17 11:26 UTC, chillenzer commented on glue_analysis/readers/read_fortran.py
> +def _normalise_vevs(vevs: pd.DataFrame, NT: int, num_configs: int) -> None:
Okay. Let's do it `pandas` style: We start out functional, i.e., create a copy as a default and, if we later on confirm that it's a memory issue, we add an `inplace=True` option. This would make the intent very clear. (If you are really unhappy with this, I would settle on making "inplace" explicit in another way, e.g., `_normalise_vevs_inplace` or the like.

2023-11-17 11:28 UTC, chillenzer commented on glue_analysis/readers/read_fortran.py
> +def _check_ensemble_divisibility(num_configs: int, num_samples: int) -> None:
Mmmhhh... thought about that but came to the conclusion that someone wanting this behaviour is very unlikely to meddle with the internals of `_read_correlators_fortran` but instead would rather turn warnings into errors.

2023-11-17 11:29 UTC, chillenzer commented on glue_analysis/readers/read_fortran.py
> +def _check_ensemble_divisibility(num_configs: int, num_samples: int) -> None:
(And you wouldn't want to drag that switch through (at least) three layers of interface to expose this behaviour.)

2023-11-17 11:44 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +def _normalise_vevs(vevs: pd.DataFrame, NT: int, num_configs: int) -> None:
As you may have guessed from my ReCoN messages, I've jumped straight to adding the `inplace` option and using it. (After convincing the linters that it's OK.)

2023-11-17 12:01 UTC, edbennett commented on glue_analysis/readers/read_fortran.py
> +def _check_ensemble_divisibility(num_configs: int, num_samples: int) -> None:
Ah, good point. We already have enough parameters.

I guess you could just set the warning tolerance in a globa— *is abruptly stuffed into a suitcase*

You've convinced me, I'll switch to a `raise` rather than a `warn`

2023-11-17 12:38 UTC, edbennett commented on test/test_read_fortran.py
> +def test_read_correlators_fortran_preserves_normalised_data_in_vev(
I've had to do a `noqa` here, because I can't work out what to type `request` as. The `pytest` docs show it as a `_pytest.mark.structures.ParameterSet`, but `_pytest` isn't publicly accessible. In principle I can do `pytest.param.__annotations__["return"]`, but `ruff` chokes on this because it mistakes `"return"` as being a forward annotation.

2023-11-17 13:08 UTC, chillenzer requested changes
Is there a test for both paths in `inplace=True/False`?

2023-11-17 13:08 UTC, chillenzer commented on test/test_read_fortran.py
> +def vev_metadata(request) -> dict[str, Any]:  # noqa: ANN001
Please, add an explaining comment for the `noqa`.

2023-11-17 13:08 UTC, chillenzer commented on test/test_read_fortran.py
> +    assert set(answer.correlators.columns) == {
Doesn't this set literal exist in `correlator.py` or `read_binary.py` already (probably as list)?

2023-11-17 13:08 UTC, chillenzer commented on test/test_read_fortran.py
> +    assert set(answer.vevs.columns) == {"MC_Time", "Internal", "Vac_exp", "channel"}
Same here.

2023-11-17 13:38 UTC, edbennett commented
There is now

2023-11-17 13:40 UTC, chillenzer commented on test/test_read_fortran.py
> +    # pytest makes it non-trivial to get the type of `request`, so annotation is omitted
Oops... forgot to mention. `request`? There is no better name for this than to copy from the documentation's example which is concerned with web stuff?

2023-11-17 13:42 UTC, chillenzer commented on test/test_read_fortran.py
> +    assert (result.Vac_exp == [0.1, 0.2, 0.3, 0.4, 0.5]).all()
Where do these magic numbers come from?

2023-11-17 13:43 UTC, chillenzer commented on test/test_read_fortran.py
> +    assert (vev_df.Vac_exp == [0.1, 0.2, 0.3, 0.4, 0.5]).all()
... and here.

2023-11-17 14:35 UTC, edbennett commented on test/test_read_fortran.py
> +    # pytest makes it non-trivial to get the type of `request`, so annotation is omitted
Having actually done the experiment now: no, `request` is hardcoded by `pytest`, you can't pick a different name. (Otherwise it goes off looking for a fixture with that name.)

2023-11-17 14:48 UTC, chillenzer commented on test/test_read_fortran.py
> +    # pytest makes it non-trivial to get the type of `request`, so annotation is omitted
Oh, wow! Didn't expect that. Sorry to have bothered you!

2023-11-17 14:55 UTC, chillenzer commented on test/test_read_fortran.py
> +    assert (result.Vac_exp == [num / normalisation for num in some_numbers]).all()
Okay, I'm sorry but I gotta ask: Why is `some_numbers` not just a `np.array` such that you could use a simple division operator here? I promise that we're done here after this one!

2023-11-17 16:50 UTC, edbennett commented on test/test_read_fortran.py
> +    assert (result.Vac_exp == [num / normalisation for num in some_numbers]).all()
Because I was lazy and didn't want to take the ten seconds to check if the `DataFrame` creation syntax I was using would work the way I wanted it to with an `ndarray`, for risk of yak shaving. Fixed.

2023-11-17 17:00 UTC, chillenzer approved these changes

2023-11-17 17:00 UTC, merged