Performance read binary
edbennett/glue_analysis pull request #42
Opened 2023-12-04 18:52 UTC by chillenzer

### Description

Moving indexing columns into `pd.MultiIndex` for performance reasons which entails minor adaptions in the functional code, moderate adaptions in the validation code and major adaptions in the test data/cases. Also using an integer enumeration of operator index and blocking level index. Could be nice to provide a function that can translate, e.g., for finding a particular operator-blocking combination. But that's likely not necessary for the use case we currently have.

### Profiles

I've profiled the code
```python3
from glue_analysis.readers.read_binary import read_correlators_binary

corr_filename = "tmp.data/corr0RPpR.dat.2"  # 394MB of data
vev_filename = "tmp.data/avac0.dat.2"  # 168KB of data
correlators = read_correlators_binary(corr_filename, vev_filename)
```

Original profile was: [profile.for-PR-orig_2023-12-04_18:10.json](https://github.com/edbennett/glue_analysis/files/13549876/profile.for-PR-orig_2023-12-04_18.10.json) (view via `scalene --viewer` and browse to the downloaded `.json` file)

It's around 5min and most of the time is spent in translating the 2x 2 columns of `Internal/Blocking_index` into an index of tuples. That function also uses significant memory, together with the actual creation of the indexing columns. Scalene reports a peak of more than 16GB which is a factor of 40 compared to the input data.

New profile is: [profile.for-PR_2023-12-04_18:04.json](https://github.com/edbennett/glue_analysis/files/13550003/profile.for-PR_2023-12-04_18.04.json)

Total execution time is down to 43s. Resource consumption of `_read_correlators_binary` (without validation) is negligible by now, 2s and 800MB which is down to a factor of 2 -- likely the price we have to pay for using Python.

Memory bottlenecks are the validation steps, particularly those concerned with ensuring consistency of the internal indexing. That was not the focus of optimisations by now. Likely there are copy operations hidden in the expressions. Time-wise the cross-validation between VEV and correlator indexing seems to be the problem. It is admittedly a bit paranoid (or more positively: assumes a very general use case) to run the check for each individual timeslice and operator.

2023-12-14 12:10 UTC, edbennett requested changes
You asked me to tear this apart, but I'm honestly having trouble—this seems a pretty clean and efficient set of changes for what we wanted to do. I've highlighted a few things that in the grand scheme of things are pretty minor.

(If there are things that you thought "I'd reject this if I were reviewing it" as you wrote it, please let me know now I've made a pass so I can learn from my misses)

2023-12-14 12:10 UTC, edbennett commented on test/test_read_binary.py
> +            range(1, int(header["LT"] / 2 + 1) + 1),
Not introduced in this PR, but why `int(thing + 1) + 1` rather than `int(thing) + 2`?

2023-12-14 12:10 UTC, edbennett commented on test/test_read_fortran.py
> +        answer.correlators.drop("channel", axis=1).to_numpy().reshape(-1) == data[:, -1]
Why not `.ravel()` instead of `.reshape(-1)`?

2023-12-14 12:10 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +    # Adding `perform_expensive_validation=False` is untested because
Not clear to me how this is untested—this code path is tested, and there are specific tests for `freeze(perform_expensive_validation=False)`.

2023-12-14 18:06 UTC, chillenzer commented on test/test_read_binary.py
> +            range(1, int(header["LT"] / 2 + 1) + 1),
Well, it's "half the lattice plus the centre point" _and_ "a `+1` for the 1-based indexing". Not really sure why it's 1-based indexing (I think it was taken over from the example data you'd given). Happy to change in either direction, i.e., the one you suggested or introducing more names and less magic constants.

2023-12-14 18:09 UTC, chillenzer commented on test/test_read_fortran.py
> +        answer.correlators.drop("channel", axis=1).to_numpy().reshape(-1) == data[:, -1]
Well spotted! For some reason, I never quite got into the habit of using `ravel`.

2023-12-14 18:13 UTC, chillenzer commented on glue_analysis/readers/read_binary.py
> +    # Adding `perform_expensive_validation=False` is untested because
Well, it is untested in the sense that a purist TDD approach would be to induce any functional change via a failing test. As long as I consider this as a functional test, this is not the case. Of course, if one considers this a refactoring -- which, coming to think about it, is probably the more appropriate categorisation -- it's totally fine. This code path is verified in many other tests (none of which could distinguish between `True` and `False` here).

2023-12-14 18:23 UTC, chillenzer commented on glue_analysis/correlator.py
> +        if perform_expensive_validation:
Yes

2023-12-14 18:23 UTC, chillenzer commented on test/test_correlator.py
> +    )
Yes, but I've changed it.

2023-12-14 19:48 UTC, chillenzer commented
PS: Considering this ready for another review/approval.

2023-12-15 11:10 UTC, edbennett commented on test/test_read_binary.py
> +            range(1, int(header["LT"] / 2 + 1) + 1),
The 1-based indexing was in turn based on the numbers output by Andreas's Fortran code, so I guess we can blame Fortran.

I think adding more names here would be the best thing, rather than leaving someone to puzzle out the logic of where the indices come from.

2023-12-15 11:37 UTC, edbennett requested changes
A few more things to think about

2023-12-15 11:37 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +@lru_cache(maxsize=8)
If we're anticipating being short on memory, do we want to be cacheing 8 full correlators (in addition to any we're holding in memory elsewhere in the code)?

2023-12-15 11:37 UTC, edbennett commented on test/test_correlator.py
> +    )
I think you changed another instance but not this one or the one below?

2023-12-15 11:37 UTC, edbennett commented on test/test_read_binary.py
>  def columns_from_header(header: dict[str, int], *, vev: bool = False) -> pd.DataFrame:
Is `columns_from_header` still a good name when it returns a `MultiIndex`?

2023-12-15 11:37 UTC, edbennett commented on test/test_read_binary.py
>  def columns_from_header(header: dict[str, int], *, vev: bool = False) -> pd.DataFrame:
Wait, this function is annotated as returning a `pd.DataFrame` but returns a `pd.MultiIndex`; how is `mypy` allowing this?

2023-12-15 11:37 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +def _columns_from_header(header: dict[str, int], columns: list[str]) -> pd.MultiIndex:
Similar to another comment, is this still the best name for this function?

2023-12-18 15:15 UTC, chillenzer commented on test/test_read_binary.py
>  def columns_from_header(header: dict[str, int], *, vev: bool = False) -> pd.DataFrame:
I was wondering the same thing (found the same thing in the functional code and fixed it). Not sure what's going on... I've tried running `mypy` with `--strict` and it complains about a bunch of decorators that we should probably fix but nothing on that.

2023-12-18 15:20 UTC, chillenzer commented
Ready to review again from my side. We're at 22 commits already. Will you get me to 25? And do we count the commit-revert?

2023-12-18 16:19 UTC, chillenzer commented
Okay. We're at 23 and all the bikes fit neatly. Anything else?

2023-12-18 16:20 UTC, merged

2023-12-18 16:21 UTC, edbennett commented
Pretty sure you committed two unicycles masquerading as a single bike in that last commit, but let's call it a day there

2023-12-18 20:37 UTC, chillenzer commented
That's only because our shed's design didn't accommodate for the need to park unicycles there. We should totally re-open and consider that possibility!