Reading multiple files
edbennett/glue_analysis pull request #49
Opened 2023-12-20 00:03 UTC by chillenzer

This works... is the best I can say about it. Well, kind of (see #46). My suggestion on how to do it right is found in #47. Also, #48.

2023-12-21 00:35 UTC, edbennett requested changes
Can't guarantee I've picked up everything (see previous discussions about effectiveness of late-night work), but some things to think about at least.

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/correlator.py
> +    if hasattr(corr_ensembles[0], "metadata"):
Should we reconcile metadata, or at least verify its consistency?

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/correlator.py
> +        corr_ensembles[0].filename, corr_ensembles[0].ensemble_name
I think `ensemble_name` has to be checked for consistency, if we're going to take using `pyerrors` seriously.

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/correlator.py
> +        corr_ensembles[0].filename, corr_ensembles[0].ensemble_name
(That will probably then make this function too long.)

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +def generate_none() -> Generator[None, None, None]:  # pragma: no cover
Does this not want to live with `NoneContext`?

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +def _handle_types(
Perhaps it'll be clear when I read further down to see where this is used, but as it stands I don't understand what this function is trying to do.

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +                _handle_types(corr_filenames, str | os.PathLike, Path),
Ah, so `_handle_types` is accounting for the fact that we need to turn a `str` into a one-element list? Either different names or a judicious comment is wanted, I think.

2023-12-21 00:35 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +    metadata_sets: dict[str, Any] | Iterable[dict[str, Any]] | None = None,
Is there any situation where we want `metadata` to be different for each file?

2023-12-21 00:35 UTC, edbennett commented on test/test_correlator.py
> +        .all()
All of these `.all().all()`s split across two lines started to rub me up the wrong way so I looked it up and apparently `.all(axis=None)` does the same thing in one line.

2023-12-21 00:35 UTC, edbennett commented on test/test_read_binary.py
> +    corr_file.truncate(
Would it make more sense to put the comment on the line before this rather than have `ruff` split a 24-character statement into 3 lines?

2023-12-21 11:57 UTC, chillenzer commented on glue_analysis/correlator.py
> +    if hasattr(corr_ensembles[0], "metadata"):
See #50.

2023-12-21 11:58 UTC, chillenzer commented on glue_analysis/readers/read_binary.py
> +def generate_none() -> Generator[None, None, None]:  # pragma: no cover
Sorry, forgot to push 3 commits.

2023-12-21 12:07 UTC, chillenzer commented on glue_analysis/correlator.py
> +        corr_ensembles[0].filename, corr_ensembles[0].ensemble_name
See #50 and #51.

2023-12-21 12:08 UTC, chillenzer commented on glue_analysis/readers/read_binary.py
> +    metadata_sets: dict[str, Any] | Iterable[dict[str, Any]] | None = None,
Yes, because we use it to communicate `MC_Time` for each ensemble. This is a very actively used feature in my use case.

2023-12-21 12:14 UTC, chillenzer commented on glue_analysis/readers/read_binary.py
> +def _handle_types(
Renamed it. Hope it's more descriptive.

2023-12-21 13:13 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +    metadata_sets: dict[str, Any] | Iterable[dict[str, Any]] | None = None,
Ah, of course.

2023-12-21 13:13 UTC, edbennett commented on glue_analysis/readers/read_binary.py
> +    metadata_sets: dict[str, Any] | Iterable[dict[str, Any]] | None = None,
Putting all kwargs into a big blob is coming back to bite us.

2023-12-22 00:03 UTC, edbennett requested changes
Almost there I think

2023-12-22 00:03 UTC, edbennett commented on glue_analysis/correlator.py
> +def concatenate(
This function could do with at least two blank lines in it to break it up, I think.

2023-12-22 00:03 UTC, edbennett commented on glue_analysis/auxiliary.py
> +        yield None
(Unless I'm misunderstanding and they do different things?)

2023-12-22 14:48 UTC, chillenzer commented
Done(?)

2023-12-22 15:34 UTC, edbennett commented on glue_analysis/correlator.py
> +def _concatenate_sane_ensembles(
Please can we use a word other than "sane"? "Sanity check" is a phrase I try to avoid as it can be considered exclusionary.

2023-12-22 15:46 UTC, edbennett commented
Stick a fork in it…

2023-12-22 15:46 UTC, merged